# print("Hello, World!")
print("Enter your lastname: ")
lastname = input()
print("Enter your firstname: ")
firstname = input()
print("Enter your age: ")
age = input()
print("Hello, " + firstname + " " + lastname+ "!" )
print(f"Hello, {firstname} {lastname}! Your age is {age}.")
print(type(lastname))
print(type(age))
print(int(age + 2))