lastname = input ("Enter your lastname: ")
firstname = input ("Enter your firstname: ")
age = int(input("Enter your age: "))
height = float(input("Enter your height: "))
print(f"Hello, {firstname} {lastname}! {age} ")
print(type(lastname))
print(type(age))
print(age + 2)
print(f'{(height + 0.1): .2f}')